on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcu:
          - stm32f401
          - stm32f405
          - stm32f407
          - stm32f410
          - stm32f411
          - stm32f412
          - stm32f413
          - stm32f415
          - stm32f417
          - stm32f423
          - stm32f427
          - stm32f429
          - stm32f437
          - stm32f439
          - stm32f446
          - stm32f469
          - stm32f479
        rust:
          - stable
        include:
          - rust: nightly
            mcu: stm32f479
            experimental: true

    steps:
      - uses: actions/checkout@v3
      - name: Use the latest ${{ matrix.rust }} rustc
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Add Cortex-M4F target
        run: rustup target add thumbv7em-none-eabihf

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: v0.16.0-${{ matrix.mcu }}

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=${{ matrix.mcu }},usb_fs,sdio-host,can,i2s,fsmc_lcd,rtic --examples
